version: '2'

services:
  redcap:
    restart: always
    env_file:
     - .env
    build:
      context: ./redcap
      args:
        smtp_server: "${SMTP_SERVER}"
        redcap_version: "${REDCAP_VERSION}"
    ports:
      - "82:80"
    volumes:
      - "${DATA_DIRECTORY}:/edocs"

